[package]
name = "flabby-ia"
version = "0.1.0"
edition = "2024"

[dependencies]
macroquad = "0.4" # Simple, rapide, parfait pour la 2D
rand = "0.10.1"      # Pour générer la hauteur des tuyaux
rayon = "1"          # Parallélisme CPU multi-cœurs pour la simulation IA

# Optimisation en mode développement (cargo run sans --release)
[profile.dev]
opt-level = 2

# Optimisation maximale pour les sessions longues (cargo run --release)
[profile.release]
opt-level = 3
lto = "thin"
codegen-units = 1